import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:rtmapp1/models/user_model.dart';

class Firestore {
  Firestore(String s);

  // just a simple get
  static Future<List<UserModel>> getAllEntries(String collection) async {
    return (await FirebaseFirestore.instance.collection(collection).get())
        .docs
        .map((item) => UserModel.fromMap(item.data()))
        .toList();
  }

  // get with custom order
  static Future<List<UserModel>> getAllEntriesSortedByName(
      String collection) async {
    return (await FirebaseFirestore.instance
            .collection(collection)
            .orderBy("manufacturer", descending: false)
            .get())
        .docs
        .map((item) => UserModel.fromMap(item.data()))
        .toList();
  }

  // get with filter
  static Future<List<UserModel>> getAllEntriesFilteredByPrice(
      String collection) async {
    return (await FirebaseFirestore.instance
            .collection(collection)
            .where("price", isGreaterThan: 60000)
            .get())
        .docs
        .map((item) => UserModel.fromMap(item.data()))
        .toList();
  }

  static Future addEntryWithAutogeneratedId(
      String collection, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance.collection(collection).add(data);
  }

  // updates an existing entry (missing fields won't be touched on update), document must exist
  static Future updateEntryWithId(
      String collection, String documentId, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .update(data);
  }

  // adds or updates an existing entry (missing fields will be deleted on update!), document will be created if needed
  static Future addOrUpdateWithId(
      String collection, String documentId, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .set(data);
  }

  // deletes the entry with the given document id
  static Future deleteEntry(String collection, String documentId) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .delete();
  }

  static getData() async {
    return await FirebaseFirestore.instance.collection('users').doc().get();
  }
}
